
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutterdeno/model/good_list_model.dart';
import 'package:flutterdeno/service/http_service.dart';

class DioMessageList extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Dio请求'),
      ),
        body: GoodListPage(),
    );
  }
}

class GoodListPage extends StatefulWidget{
  @override
  State<StatefulWidget> createState() => _GoodListPageState();
}
class _GoodListPageState extends State<GoodListPage>{

  //初始化数据模型
  Autogenerated goodListModel = Autogenerated();
  //滚动控制
  var scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    //获取商品数据
    getGoods();
  }

  void getGoods() async{
    //请求的url
    var url = 'http://apis.juhe.cn/cook/query?menu="红烧肉"&key=a9183934319a47a58bd318310124cdd1';
    var formData = {'menu': '红烧肉','rn': '10','pn': '0','key': 'a9183934319a47a58bd318310124cdd1'};

    await request(url,formData: formData).then((value) => {
      //返回数据进行json解码、转换成model
       setState((){
         goodListModel = Autogenerated.fromJson(json.decode(value.toString()));
       })
    });

  }

  Widget _ListWidget(List newList,int index){
    return Container(
      padding: EdgeInsets.only(top: 5.0,bottom: 5.0),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(
          bottom: BorderSide(width: 1.0,color: Colors.black12),
        )
      ),
      child: Row(
        children: <Widget>[
          _goodImage(newList, index),
          SizedBox(
            width: 10,
          ),
          Column(
            children: <Widget>[
              _goodsName(newList, index),
              _goodPrice(newList, index)
            ],
          )
        ],
      ),
    );
  }

  Widget _goodImage(List newList,int index){
    return Container(
      width: 150,
      height: 150,
      child: Image.network(newList[index].albums[0],fit: BoxFit.fitWidth,),
    );
  }

  //title
  Widget _goodsName(List newList,int index){
    return Container(
      padding: EdgeInsets.all(5.0),
      width: 200,
      child: Text(
        newList[index].imtro,
        maxLines: 2,
        overflow: TextOverflow.ellipsis,
        style: TextStyle(fontSize: 18),
      ),
    );
  }

  //content
  Widget _goodPrice(List newList,int index){
    return Container(
      width: 200,
      child: Text(
          '食材：${newList[index].ingredients.toString()}',
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if(goodListModel.result.data.length > 0){
      return ListView.builder(
        controller: scrollController,
        itemCount: goodListModel.result.data.length,
        itemBuilder: (context, index){
          return _ListWidget(goodListModel.result.data, index);
        },
      );
    }
    return Container();
  }

}