




class BannerModel{
  int code;
  String msg;
  List<BannerBean> data;

  BannerModel(this.data);

  BannerModel.fromJson(Map<String,dynamic> json){
    code = json['code'];
    msg = json['msg'];
    if(json['data'] != null){
      data = List<BannerBean>();
      json['data'].forEach((v){
        data.add(v);
      });
    }
  }
}
class BannerBean{
  String hrefUrl;
  int id;
  int intime;
  int orderNum;
  String path;
  int type;

  BannerBean(this.hrefUrl, this.id, this.intime, this.orderNum, this.path,
      this.type);

  BannerBean.fromJson(Map<String,dynamic> json){
    hrefUrl = json['hrefUrl'];
    id = json['id'];
    intime = json['intime'];
    orderNum = json['orderNum'];
    path = json['path'];
    type = json['type'];
  }

}








class Autogenerated{
  int error_code;
  String reason;
  Result result;
  String resultcode;

  Autogenerated({this.error_code, this.reason, this.result, this.resultcode});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error_code = json['error_code'];
    reason = json['reason'];
    result =
    json['result'] != null ? new Result.fromJson(json['result']) : null;
    resultcode = json['resultcode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error_code'] = this.error_code;
    data['reason'] = this.reason;
    if (this.result != null) {
      data['result'] = this.result.toJson();
    }
    data['resultcode'] = this.resultcode;
    return data;
  }
}

class Result {
  List<Data> data;
  String pn;
  String rn;
  String totalNum;

  Result({this.data, this.pn, this.rn, this.totalNum});

  Result.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
    pn = json['pn'];
    rn = json['rn'];
    totalNum = json['totalNum'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    data['pn'] = this.pn;
    data['rn'] = this.rn;
    data['totalNum'] = this.totalNum;
    return data;
  }
}

class Data {
  List<String> albums;
  String burden;
  String id;
  String imtro;
  String ingredients;
  List<Steps> steps;
  String tags;
  String title;

  Data(
      {this.albums,
        this.burden,
        this.id,
        this.imtro,
        this.ingredients,
        this.steps,
        this.tags,
        this.title});

  Data.fromJson(Map<String, dynamic> json) {
    albums = json['albums'].cast<String>();
    burden = json['burden'];
    id = json['id'];
    imtro = json['imtro'];
    ingredients = json['ingredients'];
    if (json['steps'] != null) {
      steps = new List<Steps>();
      json['steps'].forEach((v) {
        steps.add(new Steps.fromJson(v));
      });
    }
    tags = json['tags'];
    title = json['title'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['albums'] = this.albums;
    data['burden'] = this.burden;
    data['id'] = this.id;
    data['imtro'] = this.imtro;
    data['ingredients'] = this.ingredients;
    if (this.steps != null) {
      data['steps'] = this.steps.map((v) => v.toJson()).toList();
    }
    data['tags'] = this.tags;
    data['title'] = this.title;
    return data;
  }
}

class Steps {
  String img;
  String step;

  Steps({this.img, this.step});

  Steps.fromJson(Map<String, dynamic> json) {
    img = json['img'];
    step = json['step'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['img'] = this.img;
    data['step'] = this.step;
    return data;
  }
}